import { HashRegistryEntry } from "./crypto";

describe("HashRegistryValue", () => {
  it("should match siad for equal input", () => {
    // "h" is the hash generated by siad with the same input parameters
    const h = "3e976d957bf37f01de925e2fad2cc42eab89a7686fb57231aa6ece92e82f23d5";
    const hash = HashRegistryEntry({
      data: "abc",
      revision: 123456789,
    });
    expect(Buffer.from(hash).toString("hex")).toEqual(h);
  });
});
